### PR TITLE
Updates the documentation with new fields

### PR DESCRIPTION
**Pull request by caprenter**
Adds in the last_modified and the first_published fields with
descriptions

### CODE REVIEW

**Comment by caprenter** [comment]
You can also hopefully see the ouput of the proposed change in the json from:
http://dcdev-threesixtygiving.cs88.force.com/datastore

**Review by ekoner — APPROVED** [review]
I'm happy with the changes. Captures the 2 fields we discussed in the right format - i.e. the first is a date and second is a date-time.

**Comment by drkane** [comment]
This looks great - would be a very helpful change for importing the data into Beehive.

**Review by Bjwebb — CHANGES_REQUESTED** [review]
As discussed on a call, the descriptions look good, but the field names should be updated to match the dcat spec.

**Comment by caprenter** [comment]
Yep - d'oh. So from:
http://spec.dataportals.org/

first_published should be 'issued'
and
last_modified should be 'modified'

**Review by Bjwebb — APPROVED** [review]

**Comment by caprenter** [comment]
ok - so I've updated the code that generates the JSON, so this link will give you a sample output:
http://dcdev-threesixtygiving.cs88.force.com/datastore

I'm going to deploy that change on Monday now, so that it doesn't sit broken over the weekend should something go wrong. 

We need it to be working correctly for our purposes next week as well, so Monday should be good.

I'm happy that this is a non-breaking/backwards compatible change. I'm just slightly nervous that something could break in the deploy.

**Comment by caprenter** [comment]
I've made the update at the Salesforce endpoint, and this is now reflected in the dcat.json.

Updated this pull request with a minor change to the changelog to reflect this, so merging.

**Pull request merged**
